### PR TITLE
Documentation formatting

### PR DESCRIPTION
**Pull request by error454**
I converted the readme to markdown and tried to add some relevant section headers so things are (hopefully) easier to follow.

### CODE REVIEW

**Comment by markfguerra** [comment]
This looks great, thanks for taking the time to clear up this doc. I'd like to merge this change in.

Do you have any idea why github isn't parsing the markdown? It looks like plain text on my end.

**Comment by error454** [comment]
I _think_ the filename needs to be all caps with a lowercase extension README.md.  At least my other repos are like this and it gets parsed fine.  So lowercase extension to parse the markdown and possibly uppercase filename to get parsed on project home page.  It looks like I goofed on the extension.

**Comment by error454** [comment]
OK, should look good on your end now.

**Comment by markfguerra** [comment]
That worked. Awesome, thanks!

**Comment by markfguerra** [comment]
Would you like to be added to the NOTICE file?

**Comment by error454** [comment]
Sure, why not.  My actual name is Zach Burke.

**Pull request merged**
