### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cedroux**
- Improved Markdown (otherwise, the `<tags>` are not displayed in GitHub)
- .jar link fixed

### CODE REVIEW

**Comment by markfguerra** [comment]
Nice catch, I didn't see that tag issue :)

However the original Jar link is actually correct. I had to move the jar because [GitHub deprecated the uploads feature](https://github.com/blog/1302-goodbye-uploads), so we can't put new release binaries up on GitHub going forward.

Is the new Jar link not working for you? I've tested it from two different computers and networks, and it seems to work for me.

**Comment by cedroux** [comment]
Instead of the Jar file, I get the file **GLWallpaperService-release-v0.9.2-7f066e0.zip**, which is containing the sources.

**Comment by markfguerra** [comment]
Oh, you're right. I uploaded the wrong zip. We'll have to put together a new zip file that contains the Jar and the Docs. The link will be the same, however.

By the way, an Ant build script will be automating the creation of these release zip files going forward. I've been working on that locally.

**Comment by markfguerra** [comment]
I uploaded the correct zip, restored the link (d6a467c) and updated the NOTICE file (1c2623c). All set. Thanks.

**Pull request merged**
